server:
  port: 8091

spring:
  data:
    redis:
      host: localhost
      port: 6379

api:
  jph:
    domain: "finnhub.io"
    basepath: "/api/v1"
    endpoints:
      quote: "/quote"
      profile: "/stock/profile2"
      symbol: "/stock/symbol"
    key: "cn9ba2pr01qoee99uqmgcn9ba2pr01qoee99uqn0"